package com.cike.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-06T12:42:36.202+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.cike.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.cxf.cike.com/", className = "com.cike.cxf.ws.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.cxf.cike.com/", className = "com.cike.cxf.ws.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://ws.cxf.cike.com/", className = "com.cike.cxf.ws.GetCatsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://ws.cxf.cike.com/", className = "com.cike.cxf.ws.GetCatsByUserResponse")
    public java.util.List<com.cike.cxf.ws.Cat> getCatsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.cike.cxf.ws.User arg0
    );
}
